 version: 2.1

 orbs:
   browser-tools: circleci/browser-tools@1.3.0
   slack: circleci/slack@4.4.2

 jobs:
   build:
     docker:
       - image: cimg/python:3.9-browsers
     steps:
       - checkout
       - run:
           name: Install dependencies
           command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
       - browser-tools/install-browser-tools
       - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
       - run:
           name: Run tests
           command: |
              . venv/bin/activate
              python3 -m pytest
       - store_artifacts:
          path: reports
       - slack/notify:
          event: always
          template: (cat reports/slack_payload.json)

 workflows:
   version: 2
   commit:
     jobs:
       - build
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
